### PR TITLE
WIP new design

### PR DESCRIPTION
**Pull request by tjvr**
This is the start of a new look for the website. It aims to:

* simplify the HTML, so we can author pages in markdown
* reduce whitespace & make room for more text
* improve readability
* make photos larger, especially on mobile, now we have more photos to use
* generally look "fine": nothing too fancy
* pay particular attention to the mobile experience (50% of visitors)

Fun fact: the overwhelming majority of our visitors are using Chrome: half on Android, the other half on Windows.

I've added both a light and dark theme; it defaults to dark, but will respect the user's preference for light mode if we can.

The design uses blue as an accent color, so I've used underlining to indicate links. Important links are blue _and_ underlined. Hopefully the result shouldn't be too bad for usability.

This makes use of CSS grid, CSS variables, and inline SVG. A quick look at our analytics suggests this shouldn't be a problem; but shout if you think we shouldn't be using any of those features. The effect of no CSS variables will be that there is less color; having tested this it seems honestly fine!

Before we can merge this, we need to: 

- [x] remove unused fonts

Future work includes:

* remove all unused `<div>`s and classes
* better explaining what the tech activities actually are
* restoring the accommodation section
* making best use of our 2022 photos
* generally rewriting the home page copy

### CODE REVIEW

**Comment by tjvr** [comment]
Recent changes include:

* Introduce a new, complementary color for links. Underlining [isn't recommended](https://practicaltypography.com/underlining.html), and we can't use blue since it's our accent color. I briefly tried using a yellow highlight but it seemed too overwhelming to me.
* A more traditional button for the CTA, since what we had before was too subtle
* Finish cleaning up the index & tech HTML, in preparation for authoring them in Markdown
* Left-align the logo, and tweak its dimensions -- along with the heading dimensions
* Collapse the footer links into a vertical list on mobile
* Actually indent list items
* Correctly including bold Inter, to avoid "fake bold" on some platforms

**Comment by jamesdoc** [comment]
Can we switch the link color to `--link: #10af83;` please?

And perhaps add `text-decoration: underline` to the links?

Screenshot 2022-09-19 at 15 26 36

**Comment by jdfergusson** [comment]
To me the monospace font currently being used for the titles and such looks out of place, particularly when you're talking about small bold paragraphs the 'm's look too cramped. 
image

Any scope for changing it?

**Comment by tjvr** [comment]
I've changed the font to 
[iA Writer Duospace](https://ia.net/topics/in-search-of-the-perfect-writing-font), which isn't *quite* fixed-width: characters like "m" are a little wider, to improve readability. I think I prefer it! What do you both think?

I've also underlined the links & switched the color to the hue you suggested, after checking it against the [contrast checker](https://webaim.org/resources/linkcontrastchecker/) for both the dark and light themes.

**Comment by jdfergusson** [comment]
Looking good, one tiny thing with the new font, can we change the separator between links? 
image
Not sure I like how that looks, but shouldn't be hard to fix. Maybe vertical pipe? Maybe have them look more like buttons there actually?

**Review by jdfergusson — APPROVED** [review]

**Comment by tjvr** [comment]
@jamesdoc Are you happy for me to merge this?

**Comment by jamesdoc** [comment]
Ship it @tjvr!

**Pull request merged**
