### PR TITLE
Photos

### PR DESCRIPTION
**Pull request by tjvr**
This PR adds several new photos which were taken in 2022, and makes use of them in various places. We should still consider (re)writing (most of) the website content, but this seems like a reasonable stopgap until we do.

It's based off of #34, so let's merge that one first.

### CODE REVIEW

**Comment by jamesdoc** [comment]
Do these files get squashed as part of the deployment at a Netlify end / whacked into a `img srcset`?

**Comment by jamesdoc** [comment]
Do these files get squashed as part of the deployment at a Netlify end / whacked into a `img srcset`?

**Comment by tjvr** [comment]
They do not! ...and they're a little too big to get away with that, oops.

**Comment by tjvr** [comment]
Okay, I've replaced one photo as per @jdfergusson's request. I've also reduced the file sizes by ~90%; I'm comfortable with the current size/quality tradeoff.

**Review by jamesdoc — APPROVED** [review]

**Review by jdfergusson — APPROVED** [review]

**Pull request merged**
